export const lessons = [
  'Subject and Verb Agreement',
  'Verb Tenses',
  'if conditionals and Pronouns',
  'Comparison and Superlative and Parallel Structure',
  'Modifiers',
  'Transition Words',
  'Punctuation Marks Part 1',
  'Punctuation Marks Part 2',
  'Rhetorical Synthesis',
  'Main Ideas',
  'Making Inferences',
  'Command of Evidence - Graphs',
  'Command of Evidence - Support and Weaken',
  'Cross-Text Connections',
  'Text, Structure, and Purpose',
  'Words in Context - Gap Filling - Synonyms',
  'Supporting Evidence and Examples, Topic, Conclusion, and Transition Sentences',
  'Sentence Placement',
  'Relevance and Purpose',
  'Boundaries',
  'Form, Structure, and Sense',
  'Details Question',
  'Main Purpose',
  'Overall Structure',
  'Underlined Purpose',
  'DSAT Exam 1',
  'DSAT Exam 2',
  'DSAT Exam 3',
  'DSAT Exam 4',
  'DSAT Exam 5',
  'DSAT Exam 6',
  'DSAT Exam 7',
  'DSAT Exam 8',
  'DSAT Exam 9',
  'DSAT Exam 10',
  'EST Exam 1',
  'EST Exam 2',
  'EST Exam 3',
  'EST Exam 4',
  'EST Exam 5',
  'EST Exam 6',
  'EST Exam 7',
  'EST Exam 8',
  'EST Exam 9',
  'EST Exam 10',
  'Revision 1',
  'Revision 2',
  'Revision 3',
  'Revision 4',
  'Revision 5',
];